name: Deploy (Dev)

on:
  push:
    branches: [main]

concurrency:
  group: deploy-dev-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-dev:
    name: Deploy (Dev)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: development
    permissions:
      contents: read
    steps:
      - name: Checkout main
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          persist-credentials: false
      - name: Setup Bun environment
        uses: logica-oss/actions-toolkit/setup-bun@3caa6b132a2307a0dcbff102d1d1411a2be4107a # v1.0.1
      - name: Deploy to Cloudflare Workers
        run: bun run deploy:dev
        env:
          SITE_URL: https://dev.gophercon.jp
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
