name: Verify (Actions)

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: verify-actions-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-actions:
    uses: gopherconjp/actions-toolkit/.github/workflows/verify-actions.yaml@ea9ca5ba188f739ffba47548d4b807370d836900 # main
    permissions:
      contents: read
      checks: write
