name: Verify (Actions)

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: verify-actions-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-actions:
    uses: gopherconjp/actions-toolkit/.github/workflows/verify-actions.yaml@29fceff077d83ba6f54d9e50bcc6da900a4f4a92 # main
    permissions:
      contents: read
      checks: write
