name: Verify (Actions)

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: verify-actions-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-actions:
    uses: gopherconjp/actions-toolkit/.github/workflows/verify-actions.yaml@728f66c4d490877657abdd3dd7082556ba42a734 # main
    permissions:
      contents: read
      checks: write
